server:
  port: 8080
spring:
#  application:
#    name: user-service
#  cloud:
#    config:
#      uri: http://localhost:8888
#      fail-fast: true
#  config:
#    import: "optional:configserver:"
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li7wmgLCiGOx6rwQ
            client-secret: 3e2baac8613e8aa8ffa0dd21096f58df592df7c5
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    hostname: user-service
    non-secure-port: 8080
    prefer-ip-address: true

